"""empty message

Revision ID: 421793eea294
Revises: 
Create Date: 2019-03-05 17:43:12.549620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421793eea294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tracker',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('URL', sqlalchemy_utils.types.url.URLType(), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=200), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('execution_time', sa.DateTime(), nullable=True),
    sa.Column('request_ip', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('utc_time', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Enum('critical', 'debug', 'exception', 'info', 'warning', name='eventlevelenum'), nullable=True),
    sa.Column('event_type', sa.String(length=256), nullable=True),
    sa.Column('log_source', sa.Enum('user', name='loggersourceenum'), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_level'), 'events', ['level'], unique=False)
    op.create_index(op.f('ix_events_log_source'), 'events', ['log_source'], unique=False)
    op.create_index(op.f('ix_events_utc_time'), 'events', ['utc_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_utc_time'), table_name='events')
    op.drop_index(op.f('ix_events_log_source'), table_name='events')
    op.drop_index(op.f('ix_events_level'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_table('api_tracker')
    # ### end Alembic commands ###
