development_config: &development_config
    database_pass:          sqlite
    secret_key:             YRL28QIFXE4KQRGAVDLUJ2HJO5RAIEK6RQ3ZY23XNYYZT53HT2SKI3V57ODO5BXB

production_config:
    database_pass:          3YEP9HSH19PJ
    secret_key:             4KNUX15M5Q7MOX9T220UDOPB8X85JY0QNPILHFL8GSUVZSMI1LW7L7MJP0WGEFRL

testing_config:
    database_pass:          3YEP9HSH19PJ
    secret_key:             8OL10HO5XHIFB66JFYYPVMLML1KS2WLCW45300I3Q99YU59D0U4BQ7VX53MIFBXZ

default_config: *development_config
